module.exports.users = [
  '604133073d21f711702a9c94',
  '604133f4b3691e118e46ceec',
  '604172dc2139791491f890aa',
  '604185efe783ac168cd08213',
  '6041c3fdd8c5601be2889c0d',
  '6041c8a1a4b6af1cd37a8dfb',
  '6047fddf4f843d06ca340e18',
  '6049a2e7dc4d792e6be95ffe',
  '6049a2f8dc4d792e6be95fff',
]

module.exports.complaints = [
    'Not enough space',
    'Bad attitudes from staff and owners',
    'Bad electric hookups',
    'Gross water',
    'Dirty bathhouses and common areas',
    'Neighbor problems',
    'Unlevel sites',
    'Mud, sand, and dirt',
    'Bug issues',
    'Feeling unsafe'
]

module.exports.compliments = [
    'Nice and relaxing',
    'This is our third stay at Costanoa! We thoroughly enjoy staying there. We already have booked two more vacations. My only gripe is that no one seems to be enforcing the rules regarding dogs. There were TWO PIT BULLS running around. One of them was in the dog play area and as I walked by the dog viciously attacked the fence trying to get at me. The owner just laughed! Lights left on is an issue.',
    'Wonderful stay - campground managers were great and helpful. Upgrades to the RV sites were very nice and ocean view was beautiful.',
    'Beautiful campground and views of the ocean. Very clean and friendly staff. We enjoyed the band playing and the delicious take out food from the restaurant. Thank you',
    'A magical weekend walking along the beach, eating delicious food, and laughing with friends around the campfire.',
    'Great location! The rules are a little bit much, especially when you arrive with vacation and leisure on your mind and get hit with a bunch of conditions. Kind of a drag and a tad over-done.',
    'Nice big spots, very clean',
    'First time here, location is excellent.',
    'The grounds are well kept, the food was amazing and the majority of the staff were polite.',
    'It is so peaceful and the trees are beautiful and the view of the ocean and hearing the ocean while sleeping . . . . I LOVE it there!',
    'Wonderful location. We enjoyed the hikes behind the property that had such a beautiful view and the ones down to the beach. Look forward to returning!',
    'It was great. Grounds were very clean and the staff was great. The food at the restaurant was terrific. We had a pull through rv site. It was very small. There was no room to have an outside site up. Next time I would get a pull in site with the patio and fire pit. Other than that the place is great.',
    'This spot is amazing! The staff were incredibly friendly and helpful. The amenities are wonderful - our site had clean and sturdy table and chairs with a great fire pit and Adirondak chairs. There was even a gas grill! The views of the ocean and the hiking were off the charts great. I will definitely be back.',
    'Campgrounds are very beautiful and well kept.',
    'Campground was kept clean. Sites were comfortable size. Take out food from restaurant was scrumptious!',
    'Nice...but very expensive',
    'Certainly a winner.',
    'It was our first time there and we thought it was great. It is very clean and well taken care of. We will definitely be back!!!',
    'Had a nice view of the ocean from my camper and could hear the ocean when I went to sleep. Restroom was clean and the restaurant has really good food. All the people that work there were nice. Had a nice and relaxing time.',
    'Impressive compound with cabins, lodge , restaurant with great access and view',
    'The resort is absolutely beautiful and well kept. Enjoyed the beautiful patio with table and chairs, built-in fire pit, and barbecue.',
    'Cold, but very nice campgrounds',
    'Good views, Quiet surroundings and Cleanliness seems to be highly prioritized.',
    'Fabulous campsite and location. Your restaurant/ bar are remarkable. Excellent food and such a treat while glamping!!',
    'Our stay was excellent considering the limitations caused by CIVID. The only downside, was people walking through our site to get to the general store. You would think that they would use a little common sense and respect the privacy of others.',
    'Our new favorite place to camp. Beautiful site, with beautiful views, friendly staff. Really enjoyed the food from Cascades, and getting treats from the general store. The highlight was seeing all the elephant seals at the beach!',
    'Great campground and amenities. Maybe upgrade the WiFi access in the Eucalyptus loop.',
    'Everything was clean and all landscape areas well maintained with trash areas cleaned out at all times.',
    'Great place to go and relax!',
    'Most amenities were closed due to Covid. I am sure it would be a 10 once everything re-opens. Security was a little over the top.',
    'Excellent property. Excellent staff. You should open up more tent sites and give them sun and ocean views.',
    'Loved the location and proximity to the ocean. Campsite was very clean and well equipped. The section we stayed in had its own gas grills and fire pits available. Very nice to have a large grass field in the middle of the circle. Staff was excellent.',
    'Beautiful campground. Staff was wonderful and the grounds are well maintained. We stay in seascape and the sites were worth the cost. We will be back.'
]